Update openstreetmap-carto-hstore-only-l10n.lua - Switching from `add_row()` to `insert()` for osm2pgsql
giggls/osml10n pull request #40
Opened 2024-08-16 13:33 UTC by astridx

Here's an English PR description for the issue you worked on:

---

### Background:
I came across the open question in Issue [#4977](https://github.com/gravitystorm/openstreetmap-carto/issues/4977) regarding the potential impact on the German style of OpenStreetMap. To investigate further, I set up a test environment and tested the installation of the openstreetmap.de tile server using the latest version of `osm2pgsql`.

```bash
$ osm2pgsql --version
osm2pgsql version 1.11.0 (1.11.0-136-gf8c78ae3)
Build: RelWithDebInfo
Compiled using the following library versions:
Libosmium 2.20.0
Proj 9.1.1
Lua 5.3.6
```

During the data import process using the following command:

```bash
sudo -u _tirex osm2pgsql -c -d osm --slim -C 0 -O flex \
  --number-processes 1 -S /srv/tile/sources/osml10n/openstreetmap-carto-hstore-only-l10n.lua \
  /srv/tile/planet.osm.pbf
```

I encountered the following error:

```
ERROR: Error loading lua config: ...sources/osml10n/openstreetmap-carto-hstore-only-l10n.lua:81: Error in 'define_table': Unknown column type 'area'. (https://github.com/giggls/osml10n/blob/master/openstreetmap-carto-hstore-only-l10n.lua#L81)
```

### Solution:
Sarah pointed me to this [tutorial](https://osm2pgsql.org/doc/tutorials/switching-from-add-row-to-insert/), which I have now integrated into the Lua script.

### Notes:
This version is likely not perfect; there is redundant code, specifically in the functions `add_multiroads` and `add_roads`  (`add_polygons` and `add_polygons`), which could potentially be combined into a single function by checking the type. However, the current implementation works because the multi function is always called from process_relation, ensuring that the types align correctly and my knowledge of the types is limited, and since this solution works, I'm submitting it for your review as is.

2024-08-16 14:00 UTC, joto requested changes
As you mention there is still quite some code duplication here. Two (mutually exclusive) ideas for you to consider:

1. All the `add_*` functions have a `tags` and a new `object`. If you keep the object parameter, then the tags parameter is superfluous, because you can just call `object.tags` to get it.
2. Consider using a `geom` parameter instead of the `object` parameter. This is initialized outside the function with `object:as_linestring()` or `object:as_multipolygon()` or whatever. Then there are fewer versions of those functions, because inside you can use that geometry and do the merging and segmentizing and so on. So you don't need two sets of functions for the non-multi and the multi case.

Also the basic settings of the `cols` should really go into its own function, it seems to be the same everywhere. But that was already a problem in the old code.

2024-08-16 14:00 UTC, joto commented on openstreetmap-carto-hstore-only-l10n.lua
> +        tables.line:insert({ cols })
The `{}` around the `cols` is wrong. Some of the other functions have the same problem, some are correct.

2024-08-19 13:07 UTC, astridx commented on openstreetmap-carto-hstore-only-l10n.lua
> +        tables.line:insert({ cols })
Thanks

2024-08-21 10:35 UTC, astridx commented
> As you mention there is still quite some code duplication here. Two (mutually exclusive) ideas for you to consider:
> 
>     1. All the `add_*` functions have a `tags` and a new `object`. If you keep the object parameter, then the tags parameter is superfluous, because you can just call `object.tags` to get it.
> 
>     2. Consider using a `geom` parameter instead of the `object` parameter. This is initialized outside the function with `object:as_linestring()` or `object:as_multipolygon()` or whatever. Then there are fewer versions of those functions, because inside you can use that geometry and do the merging and segmentizing and so on. So you don't need two sets of functions for the non-multi and the multi case.
> 
> 
> Also the basic settings of the `cols` should really go into its own function, it seems to be the same everywhere. But that was already a problem in the old code.

Thanks for the tip. I have tackled the second variant here:
https://github.com/giggls/osml10n/pull/40/commits/a897f7f9c54d5d0019a79cdcd0caf44492a36834

Why do you mean/suggest that it is better to place the basic settings of the column in a separate function?

2024-08-21 11:43 UTC, joto commented
It looks to me that this here is the same in all functions, it it not?

```
    local cols = {}
    cols.tags = tags
    cols['layer'] = layer(tags['layer'])
    cols['z_order'] = z_order(tags)
    cols.name_l10n = name_l10n
```

So it makes sense to factor this out and do it in one function for all cases.

2024-08-21 11:54 UTC, giggls commented
Just for your info. This code is derived from an earlier version of a legacy compatible flex output port which @pnorman did for upstream osm-carto adapted to the hstore-only setup I use in German style.

2024-08-21 14:13 UTC, joto commented
@giggls I hope you know that I did a newer version of that. See [the issue](https://github.com/gravitystorm/openstreetmap-carto/issues/4977) and this [PR](https://github.com/gravitystorm/openstreetmap-carto/pull/4978). There is a chance that this will get merged at some point. Ideally we would get this in sync with what you are using in some way, for instance by creating specific hook points for extensions.

2024-08-21 14:41 UTC, giggls commented
I do. However, the database layout of German style predates the upstream usage of hstore. It differs in the way that I moved everything to hstore while upstream kept the columns it had before just adding hstore for the rest. I liked my version more and while I was working with views anyway I just kept what I had. I am still able to render upstream though.

2024-10-21 11:26 UTC, merged